In [1]:
import numpy as np
print(np.__version__)

2.3.5


In [8]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
b = np.array([[1,2],[2,3],[3,4],[4,5]])
print(b)
print(type(b))

[[1 2]
 [2 3]
 [3 4]
 [4 5]]
<class 'numpy.ndarray'>


In [15]:
c = np.array([[[1]],[[2]],[[3]],[[4]]])
print(c)
print(c.ndim)

[[[1]]

 [[2]]

 [[3]]

 [[4]]]
3


In [16]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
e = np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
np.full((4,4),11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [23]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
f = np.array(["I am here", "I am nowhere"])
print(f)

['I am here' 'I am nowhere']


In [33]:
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)
print(f.dtype)

(4, 1, 1)
3
4
int64
<U12


In [34]:
f[0] = "I am everywhere now" 
print(f[0])
# Output: 'I am every' (Truncated to 10 chars)   

I am everywh


In [35]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
c = b.flatten()
print(c)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
print(b.ravel())
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
a = np.array([18, 19, 20, 21, 22])
b = np.array([1, 2, 3, 4, 5])
m  = b < 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a < b)
print(a == b)
print(b <= 4)
# print(a[b])
print(b[m])

[19 21 23 25 27]
[17 17 17 17 17]
[ 18  38  60  84 110]
[18.          9.5         6.66666667  5.25        4.4       ]
[0 1 2 1 2]
[False False False False False]
[False False False False False]
[ True  True  True  True False]
[1 2]


In [64]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.percentile(a, 45))
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))


100
20.0
20.0
1.4142135623730951
2.0
18
22
19.8
[4.24264069 4.35889894 4.47213595 4.58257569 4.69041576]
[2.89037176 2.94443898 2.99573227 3.04452244 3.09104245]
[6.56599691e+07 1.78482301e+08 4.85165195e+08 1.31881573e+09
 3.58491285e+09]
[-0.75098725  0.14987721  0.91294525  0.83665564 -0.00885131]


In [67]:
a = np.array([18, 19, 20, 21, 22])
b = np.array([1])

print(a+b)

[19 20 21 22 23]
