In [5]:
import numpy as np

In [39]:
#student marks analysis system (usin numpy)
#dataset creation
rng = np.random.default_rng()

# 100 students, 5 subjects
student_marks = rng.integers(35, 101, size=(35, 5))

subjects = ["Math", "Science", "English", "Computer", "History"]
student_names = ["Aarav","Vivaan","Aditya","Arjun","Krishna","Rohan","Rahul","Karan","Yash","Harsh","Ananya","Diya","Priya","Aditi",
"Sneha","Kavya","Meera","Ishita","Riya","Neha","Akash","Siddharth","Manav","Nikhil","Varun","Tanvi","Sanya","Pooja","Muskan","Simran",
"Dev","Aryan","Shreya","Aniket","Palak"]

print(student_marks)
print(student_marks.shape)

[[ 36  82  36  92  45]
 [ 68  57  69  83  46]
 [ 47  51  80  89  87]
 [ 97  38  88  50  80]
 [ 37  92  88  47  37]
 [ 57 100  64 100  92]
 [ 56  83  48  90  78]
 [ 94  46  95  66  37]
 [ 58  57 100  35  55]
 [ 51  79  97  71  62]
 [ 54  77  47  98  70]
 [ 80  84  78  71  84]
 [ 54  66  46  55  76]
 [ 84  51  98  82  94]
 [ 72  57  41  99  88]
 [ 62  65  70  84  84]
 [ 60  38  82  55  67]
 [ 93  44  36  66  44]
 [ 77  51  51  67  47]
 [ 62  90  88  42  98]
 [100  54  56  44  87]
 [ 70  94  45  50  46]
 [ 70  43  93  99  69]
 [ 70  78  50  59  82]
 [ 59  89  76  94  59]
 [ 55  67  50  95  87]
 [ 74  91  83  74  71]
 [ 39  90  83  71  96]
 [100  62  93  39  76]
 [ 75  70  73  66  70]
 [ 84  53  61  91  83]
 [ 61  83  47  69  52]
 [ 69  42 100  43  94]
 [ 63  54  51  65 100]
 [ 71  81 100  73  80]]
(35, 5)


In [17]:
avg_marks = np.mean(student_marks, axis=1)
print(avg_marks)

[63.4 77.2 80.8 75.4 70.4 69.4 72.  47.2 89.  52.8 70.8 75.  59.2 65.4
 75.  65.4 62.4 50.8 75.8 57.4 62.6 89.8 52.4 57.  62.4 77.8 62.8 63.4
 61.4 78.2 59.6 81.4 75.6 68.2 72.2]


In [21]:
highest = np.max(student_marks)
lowest = np.min(student_marks)

print(highest)
print(lowest)

100
35


In [28]:
std_dev = np.std(student_marks, 1)

print(std_dev)

[27.3100714  17.63405796 19.11439248 19.93589727 25.03277851 20.02598312
  9.85900604  8.65794433  6.95701085  9.76524449 16.48514483 21.76235281
 23.70147675 20.08581589  7.04272674 20.8        22.08710031  7.67854153
 13.19696935 16.66853323 17.74936619  8.35224521 13.63231455 12.23110788
 15.00133327 17.97108789 15.68948693 12.27354879 18.17250671 14.6342065
 17.92874786 19.37627415 18.22745182 17.26731016 11.01635148]


In [50]:
ranking = np.argsort(avg_marks)[::-1]

for i in range(len(student_names)):
    print(f"{student_names[i]}: Rank {ranking[i]+1}")

Aarav: Rank 22
Vivaan: Rank 9
Aditya: Rank 32
Arjun: Rank 3
Krishna: Rank 30
Rohan: Rank 26
Rahul: Rank 2
Karan: Rank 19
Yash: Rank 33
Harsh: Rank 4
Ananya: Rank 15
Diya: Rank 12
Priya: Rank 35
Aditi: Rank 7
Sneha: Rank 11
Kavya: Rank 5
Meera: Rank 6
Ishita: Rank 34
Riya: Rank 14
Neha: Rank 16
Akash: Rank 1
Siddharth: Rank 28
Manav: Rank 27
Nikhil: Rank 21
Varun: Rank 17
Tanvi: Rank 25
Sanya: Rank 29
Pooja: Rank 31
Muskan: Rank 13
Simran: Rank 20
Dev: Rank 24
Aryan: Rank 10
Shreya: Rank 23
Aniket: Rank 18
Palak: Rank 8


In [51]:
class_average = np.mean(avg_marks)

top_students = np.where(avg_marks > class_average)[0]

print(*(student_names[i] for i in top_students), sep=", ")

Vivaan, Aditya, Arjun, Krishna, Rohan, Rahul, Yash, Ananya, Diya, Sneha, Riya, Siddharth, Tanvi, Simran, Aryan, Shreya, Aniket, Palak


In [36]:
subject_average = np.mean(student_marks, axis=0)
subject_highest = np.max(student_marks, axis=0)
subject_lowest = np.min(student_marks, axis=0)

print(subject_average)
print(subject_highest)
print(subject_lowest)

[63.31428571 67.37142857 70.62857143 63.62857143 67.37142857]
[100 100 100  97  98]
[37 38 35 35 35]


In [38]:
total_marks = np.sum(student_marks, axis=1)

percentage = (total_marks / 500) * 100

print(percentage)

[64.2 65.4 72.4 81.6 66.2 72.6 59.8 56.4 64.8 79.  76.  61.8 78.4 55.4
 73.4 55.6 71.6 70.8 72.2 58.6 46.  50.4 63.8 66.  63.  77.8 63.2 66.2
 71.4 69.4 56.2 60.8 74.4 66.4 75. ]
